const followers = [
  {
    code: "facebook",
    color: "bg-facebook",
    icon: "./images/icon-facebook.svg",
    user: "@nathanf",
    numF: 1987,
    rate: 12,
    up: true,
  },
  {
    code: "twitter",
    color: "bg-twitter",
    icon: "./images/icon-twitter.svg",
    user: "@nathanf",
    numF: 1044,
    rate: 99,
    up: true,
  },
  {
    code: "instagram",
    color: "bg-gradient-to-r from-from to-to",
    icon: "./images/icon-instagram.svg",
    user: " @realnathanf",
    numF: 11,
    rate: 1099,
    up: true,
  },
  {
    code: "youtube",
    color: "bg-youtube",
    icon: "./images/icon-youtube.svg",
    user: " @Nathan F.",
    numF: 8239,
    rate: 144,
    up: false,
  },
];
const overviews = [
  {
    title: "Page Views",
    icon: "./images/icon-facebook.svg",
    numO: 87,
    rate: 3,
    up: true,
  },
  {
    title: "Likes",
    icon: "./images/icon-facebook.svg",
    numO: 52,
    rate: 2,
    up: false,
  },
  {
    title: "Likes",
    icon: "./images/icon-instagram.svg",
    numO: 5462,
    rate: 2257,
    up: true,
  },
  {
    title: "Profile Views",
    icon: "./images/icon-instagram.svg",
    numO: 52,
    rate: 1375,
    up: true,
  },
  {
    title: "Retweets",
    icon: "./images/icon-twitter.svg",
    numO: 117,
    rate: 303,
    up: true,
  },
  {
    title: "Likes",
    icon: "./images/icon-twitter.svg",
    numO: 507,
    rate: 553,
    up: true,
  },
  {
    title: "Likes",
    icon: "./images/icon-youtube.svg",
    numO: 107,
    rate: 19,
    up: false,
  },
  {
    title: "Total Views",
    icon: "./images/icon-youtube.svg",
    numO: 1407,
    rate: 12,
    up: false,
  },
];
export { followers, overviews };
